### ISSUE TITLE
!*If control structure tag

### ISSUE THREAD

**Issue by anti-social** [anti-social/yet#1]
1. **Vanishing node**

```yaml
---
- 0
- !*If
  condition: true
  then: [1, 2]
- 3
---
- 0
- 1
- 2
- 3
```
Problems:

- Scalar into a list entry
```yaml
---
- 0
-
  # One more level
  - !*If
    condition: true
    then: 1
    else: 2
- 3
```

- Need some key in a map
```yaml
---
x:
  a: 0
  # It looks a bit ugly
  _1: !*If
    condition: true
    then: {b: 1, c: 2}
```

2. **Before & after**

```yaml
---
### Inserting into middle of a list
x: !*If
  condition: true
  before:
  - 0
  then:
  - 1
  - 2
  after:
  - 3
---
x:
- 0
- 1
- 2
- 3
```

Problems:

- a lot of garbage

- Insert into a map - before and after are not clear names
```yaml
!*If
condition: true
before:
  a: 0
then:
  b: 1
  c: 2
after:
  d: 3
```

3. **Unpack**

Default mode:
```yaml
---
- 0
- !*If
  condition: true
  then: [1, 2]
- 3
---
- 0
-
  - 1
  - 2
- 3
```

Unpack into a list:
```yaml
---
- 0
- !*If
  condition: true
  unpack: true
  then: [1, 2]
- 3
---
- 0
- 1
- 2
- 3
```

Problems:

- Unpack into middle of a map:
```yaml
---
x:
  a: 0
  # Also need that ugly name
  _1: !*If
    condition: true
    unpack: true
    then: {b: 1, c: 2}
  d: 3
```

4. **External unpack**

Requires processing on a lower level: `*If` must be processed before `*Unpack`.

```yaml
---
- 0
- !*Unpack
  - !*If
    condition: true
    then: [1, 2]
- 3
```

**Comment by anti-social** [comment]
Is it possible to use `<<` for unpacking into a map:
```yaml
---
x:
  a: 0
  <<: !*If
    condition: true
    then: {b: 1, c: 2}
  d: 3
```
