### ISSUE TITLE
!*Each control structure tag

### ISSUE THREAD

**Issue by anti-social** [anti-social/yet#2]
`!*Each` tag to duplicate config parts.

- List:
```yaml
---
!*Each
items:
- pos: 1
  name: Mc Queen
- pos: 2
  name: Sally
loop: 
- ${{item.name}} took ${{item.pos}} place

---
- Mc Queen took 1 place
- Sally took 2 place
```

- Map:
```yaml
---
commands: !Each
  items: [unit, func]
  loop:
    test.${{item}}:
      cmd: test --${{item}}

---
commands:
  test.unit:
    cmd: test --unit
  test.func:
    cmd: test --func
```
