### ISSUE TITLE
!*EachDocument

### ISSUE THREAD

**Issue by anti-social** [anti-social/yet#3]
Same as `!*Each` but generates multiple documents:

```yaml
---
!*EachDocument
items:
- name: rest
  port: 8000
- name: grpc
  port: 50001
loop:
  kind: Deployment
  name: app-${{item.name}}
  port: ${{item.port}}
```

produces:
```yaml
---
kind: Deployment
name: app-rest
port: 8000
---
kind: Deployment
name: app-grpc
port: 50001
```
